// Mock data for export page development
export const mockExportData = {
  child: {
    id: 'mock-child-1',
    name: 'Emma',
    lastName: 'Dupont',
    image: '/placeholder-girl.png',
    age: 8,
    gender: 'FEMALE' as EGender,
    program: {
      id: 'mock-program-1',
      name: 'Programme CE2',
      description: 'Programme officiel CE2 adapté pour l\'instruction en famille',
      grade: 'CE2',
      elements: [],
      children: [],
      createdAt: new Date('2024-09-01'),
      updatedAt: new Date('2024-12-15'),
    },
    journalEntries: [],
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-12-15'),
  } as IChild,

  journalEntries: [
    {
      id: 'mock-entry-1',
      date: new Date('2024-12-10'),
      comment: 'Aujourd\'hui, Emma a travaillé sur les fractions. Elle a bien compris le concept de moitié et de quart en utilisant des pizzas en papier. Nous avons aussi fait de la lecture avec "Le Petit Prince" - elle a lu 2 pages toute seule !',
      images: [
        'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkZyYWN0aW9ucyBhdmVjIHBpenphczwvdGV4dD48L3N2Zz4=',
      ],
      validatedElements: [
        {
          id: 'mock-element-1',
          name: 'Comprendre les fractions simples (1/2, 1/4)',
          description: 'Identifier et représenter les fractions simples dans des situations concrètes',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-10'),
        },
        {
          id: 'mock-element-2',
          name: 'Lecture fluide de textes adaptés',
          description: 'Lire à voix haute avec fluidité un texte d\'une dizaine de lignes',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-10'),
        },
      ],
      child: {} as IChild, // Will be filled by reference
      createdAt: new Date('2024-12-10'),
      updatedAt: new Date('2024-12-10'),
    },
    {
      id: 'mock-entry-2',
      date: new Date('2024-12-09'),
      comment: 'Séance de sciences sur les états de la matière. Emma a observé la fonte de glaçons et l\'évaporation de l\'eau. Elle a dessiné ses observations dans son cahier de sciences.',
      images: [
        'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkV4cMOpcmllbmNlIGdsYcOnb25zPC90ZXh0Pjwvc3ZnPg==',
        'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkRlc3NpbnMgZCdvYnNlcnZhdGlvbjwvdGV4dD48L3N2Zz4=',
      ],
      validatedElements: [
        {
          id: 'mock-element-3',
          name: 'Observer les états de la matière',
          description: 'Identifier les trois états de la matière et leurs transformations',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-09'),
        },
        {
          id: 'mock-element-4',
          name: 'Réaliser un dessin d\'observation',
          description: 'Dessiner en respectant les proportions et en ajoutant des légendes',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-09'),
        },
      ],
      child: {} as IChild,
      createdAt: new Date('2024-12-09'),
      updatedAt: new Date('2024-12-09'),
    },
    {
      id: 'mock-entry-3',
      date: new Date('2024-12-08'),
      comment: 'Mathématiques : révision des tables de multiplication. Emma maîtrise maintenant les tables de 2, 5 et 10. Nous avons utilisé des jeux de cartes pour rendre l\'apprentissage plus ludique.',
      images: [],
      validatedElements: [
        {
          id: 'mock-element-5',
          name: 'Connaître les tables de multiplication (2, 5, 10)',
          description: 'Mémoriser et utiliser les tables de multiplication de 2, 5 et 10',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-08'),
        },
      ],
      child: {} as IChild,
      createdAt: new Date('2024-12-08'),
      updatedAt: new Date('2024-12-08'),
    },
    {
      id: 'mock-entry-4',
      date: new Date('2024-12-07'),
      comment: 'Sortie pédagogique au musée d\'histoire naturelle. Emma a été fascinée par les dinosaures et a posé beaucoup de questions. Elle a pris des notes et des croquis pour son dossier sur la préhistoire.',
      images: [
        'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPk11c8OpZSBkaW5vc2F1cmVzPC90ZXh0Pjwvc3ZnPg==',
      ],
      validatedElements: [
        {
          id: 'mock-element-6',
          name: 'Se repérer dans le temps : la préhistoire',
          description: 'Situer la préhistoire sur une frise chronologique et connaître ses caractéristiques',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-07'),
        },
        {
          id: 'mock-element-7',
          name: 'Prendre des notes et faire des croquis',
          description: 'Organiser ses observations par écrit et par le dessin',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-07'),
        },
      ],
      child: {} as IChild,
      createdAt: new Date('2024-12-07'),
      updatedAt: new Date('2024-12-07'),
    },
    {
      id: 'mock-entry-5',
      date: new Date('2024-12-06'),
      comment: 'Atelier d\'écriture créative. Emma a écrit une petite histoire sur un chat magique. Nous avons travaillé sur la structure du récit (début, milieu, fin) et l\'utilisation des adjectifs pour enrichir les descriptions.',
      images: [],
      validatedElements: [
        {
          id: 'mock-element-8',
          name: 'Écrire un récit de fiction',
          description: 'Rédiger un texte narratif en respectant la chronologie et en utilisant des connecteurs',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-06'),
        },
        {
          id: 'mock-element-9',
          name: 'Enrichir ses phrases avec des adjectifs',
          description: 'Utiliser des adjectifs qualificatifs pour préciser et enrichir ses écrits',
          isValidated: true,
          journalEntries: [],
          children: [],
          programId: 'mock-program-1',
          createdAt: new Date('2024-09-01'),
          updatedAt: new Date('2024-12-06'),
        },
      ],
      child: {} as IChild,
      createdAt: new Date('2024-12-06'),
      updatedAt: new Date('2024-12-06'),
    },
  ] as IJournalEntry[],
}

// Fill child references in journal entries
mockExportData.journalEntries.forEach((entry) => {
  entry.child = mockExportData.child
})
