/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/compte': RouteRecordInfo<'/compte', '/compte', Record<never, never>, Record<never, never>>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/enfant/[name]': RouteRecordInfo<'/enfant/[name]', '/enfant/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/enfants': RouteRecordInfo<'/enfants', '/enfants', Record<never, never>, Record<never, never>>,
    '/export/pdf/': RouteRecordInfo<'/export/pdf/', '/export/pdf', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mot-de-passe-oublie': RouteRecordInfo<'/mot-de-passe-oublie', '/mot-de-passe-oublie', Record<never, never>, Record<never, never>>,
    '/reinitialisation': RouteRecordInfo<'/reinitialisation', '/reinitialisation', Record<never, never>, Record<never, never>>,
    '/verification': RouteRecordInfo<'/verification', '/verification', Record<never, never>, Record<never, never>>,
  }
}
